apiVersion: v1
kind: Service
metadata:
  name: LoadBalancer
spec:
  selector:
    app: tanzu
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 31981
  externalIPs:
    - 1.2.4.120
